language: generic
dist: bionic
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y texlive tex-gyre texlive-luatex lmodern  texlive-xetex texlive-latex-base texlive-latex-extra texlive-lang-polish texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-science latexmk xzdec

cache:
  directories:
    - /tmp/texlive

before_script:
  - mkdir ~/.fonts
  - cp $TRAVIS_BUILD_DIR/fonts/* ~/.fonts/
  - cd $TRAVIS_BUILD_DIR/docs/

script:
  - latexmk -xelatex *.tex

before_deploy:
  - git config --local user.name "hjaremko"
  - git config --local user.email "hjaremko@outlook.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - find ./ -name '*.pdf' | xargs zip wmii-wzory-dokumentow-$TRAVIS_TAG.zip

deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file:
    - ./*.pdf
    - ./**/*.pdf
    - ./tcs/**/*.pdf
    - wmii-wzory-dokumentow-*.zip
  skip_cleanup: true
  overwrite: true
  on:
    # branch: master
    all_branches: true
